services:
  app:
    volumes:
      - ./app:/app/app  # hot reload for development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    environment:
      - DEBUG=True
      - LOG_LEVEL=DEBUG