services:
  # ATABOT 2.0 Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atabot_app
    restart: unless-stopped
    env_file:
      - .env # Pastikan DATABASE_URL di file ini sudah benar
    ports:
      - '8000:8000'
    volumes:
      - ./logs:/app/logs # Persist logs
    networks:
      - atabot_network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/api/v1/health/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      # Variabel ini akan diambil dari file .env Anda
      - DATABASE_URL=${DATABASE_URL}
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}
      - POE_API_KEY=${POE_API_KEY}
    # Pastikan app bergantung pada redis jika Anda menggunakannya
    depends_on:
      - redis

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: atabot_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - atabot_network

networks:
  atabot_network:
    driver: bridge

volumes:
  redis_data:
    driver: local